[package]
name = "ch-client"
version = "0.0.0"
description = "clickhouse client"
edition = "2018"
publish = false
license = "Proprietary"

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "select"
harness = false

[dependencies]
thiserror = "1.0.16"
serde = "1.0.106"
bytes = "0.5.4"
tokio = { version = "0.2.20", features = ["rt-core", "stream"] }
hyper = "0.13.5"
url = "2.1.1"
reflection = "0.1.3"
reflection_derive = "0.1.1"
smallvec = "1.4.0"
futures = "0.3.5"

[dev-dependencies]
criterion = "0.3.2"
serde = { version = "1.0.106", features = ["derive"] }
tokio = { version = "0.2.20", features = ["full"] }
serde_bytes = "0.11.4"

