[package]
name = "clickhouse"
version = "0.2.0"
description = "a typed client for ClickHouse"
keywords = ["clickhouse", "database", "driver", "tokio"]
authors = ["Paul Loyd <pavelko95@gmail.com>"]
repository = "https://github.com/loyd/clickhouse.rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "select"
harness = false

[dependencies]
thiserror = "1.0.16"
serde = "1.0.106"
bytes = "0.5.4"
tokio = { version = "0.2.20", features = ["rt-core", "stream"] }
hyper = "0.13.5"
url = "2.1.1"
reflection = "0.1.3"
reflection_derive = "0.1.1"
smallvec = "1.4.0"
futures = "0.3.5"
sha-1 = "0.9.1"

[dev-dependencies]
criterion = "0.3.2"
serde = { version = "1.0.106", features = ["derive"] }
tokio = { version = "0.2.20", features = ["full"] }
serde_bytes = "0.11.4"
